# This is a basic workflow that is manually triggered

name: Manual workflow4

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: test things
        run: |
          ls -l
      - name: checks installation pandoc
        run: |
          which pandoc
      - name: push directory
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
        run: |
          sh ./push-to-another-git.sh /home/work/testHelm/testHelm mtricentis helm2
          #sh ./push.sh
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.4.0 #renovate: datasource=github-releases depName=helm/helm
      - name: Add external Helm repos
        run: helm repo add reloader https://stakater.github.io/stakater-charts
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: Charts
          # version: v1.1.1 # renovate: datasource=github-releases depName=helm/chart-releaser
        env:
          CR_TOKEN: '${{ secrets.API_GITHUB_TOKEN }}'
     
